import { PRODUCT_PATH } from '../../utils/constants'

export const LOAD = `${PRODUCT_PATH}/LOAD`
export const REDIRECT = `${PRODUCT_PATH}/REDIRECT`
export const FETCH_PRODUCTS = `${PRODUCT_PATH}/FETCH_PRODUCTS`
export const SET_PRODUCTS = `${PRODUCT_PATH}/SET_PRODUCTS`
export const SET_PRODUCT = `${PRODUCT_PATH}/SET_PRODUCT`
export const ADD_PRODUCT = `${PRODUCT_PATH}/ADD_PRODUCT`
export const DELETE_PRODUCT = `${PRODUCT_PATH}/DELETE_PRODUCT`
export const UPDATE_PRODUCT = `${PRODUCT_PATH}/UPDATE_PRODUCT`
